### ISSUE TITLE
playplay.io rank command returns users not on our team

### ISSUE THREAD

**Issue by jbcpollak** [dblock/slack-gamebot#104]
When we run `@pongbot rank` we get a dump of 100s of users not on our team. In addition to being annoying, it's probably some what of a security risk since it leaks handles from other user's Slack accounts.

`@pongbot leaderboard` doesn't seem to have this problem.

See screenshot (the full post is many pages long):

<img width="419" alt="screen shot 2016-04-27 at 7 31 12 pm" src="https://cloud.githubusercontent.com/assets/188558/14871263/a415f634-0cae-11e6-934b-dffa31cba17a.png">

**Comment by dblock** [comment]
This has been fixed, thanks for reporting it.

Please consider sponsoring my open-source work and the playplay.io service with a 100$ donation, get your company logo on http://playplay.io and keep the service free for everyone else. Click [here](https://www.paypal.me/playplay/100). See http://playplay.io/#sponsors for more info.

**Comment by jbcpollak** [comment]
Thanks for the rapid response! We just got our pingpong table setup yesterday - if we adopt pongbot we will consider sponsorship. :)

Also related to rank, I am unranked, when I run `pongbot rank` I get the following output (my handle is `undefined`):

```
pongbotBOT [8:37 AM] 
undefined: not ranked
dreadpirateroberts: not ranked
tim: not ranked
```

It seems to be showing everyone who is unranked. The same is true for `pongbot rank undefined`.

But if I run `pongbot rank fuzzball`, I see:

```
2. fuzzball: 0 wins, 1 loss (elo: -48)
```

Is this expected behavior?

**Comment by jbcpollak** [comment]
BTW - We probably overlapped at Dog Patch - I was CTO at Assured Labor.

**Comment by dblock** [comment]
That looks like a bug too. Care to open a new one, I'll take a look at fixing it. Also don't hesitate to PR a fix yourself :)

**Comment by jbcpollak** [comment]
I looked into it, but I'm not a Ruby dev so jumping in might be difficult. I'll open a separate bug.
