### ISSUE TITLE
"lost" does not verify that a match has taken place before recording the loss.

### ISSUE THREAD

**Issue by hubbazoot** [dblock/slack-gamebot#108]
When there is no active match, using "gamebot lost 0-1" will record a loss against the previous opponent played.

![untitled](https://cloud.githubusercontent.com/assets/2689544/15296854/8cabad5e-1b54-11e6-93be-704f7b6412e3.png)

**Comment by hubbazoot** [comment]
Update: It appears that this does not actually record the match, it just displays the dialogue like as though it has.

**Comment by dblock** [comment]
It updates the previous match by design and says _match scores have been updated_. What do you think it should do differently or say?

**Comment by hubbazoot** [comment]
Wow, I completely missed that. Sorry!

**Comment by dblock** [comment]
:)

Please consider sponsoring my open-source work and the playplay.io service with a 100$ donation, get your company logo on http://playplay.io and keep the service free for everyone else. Click [here](https://www.paypal.me/playplay/100). See http://playplay.io/#sponsors for more info.
