### ISSUE TITLE
Matches recorded with "lost to" are not recorded in the matches history?

### ISSUE THREAD

**Issue by hubbazoot** [dblock/slack-gamebot#112]
When viewing the "matches" list, matches appear to be missing from the list, a recent game recorded with "lost to" appears not to be on the list, but several that were created as challenges appear to be recorded.

**Comment by dblock** [comment]
Fixed in https://github.com/dblock/slack-gamebot/commit/a4e38a8803dbec70399838ca3f7782c806f5da93.
