### ISSUE TITLE
Allow unbalanced teams

### ISSUE THREAD

**Issue by dblock** [dblock/slack-gamebot#124]
See https://github.com/AlexLaviolette/slack-gamebot/commit/4b0c77a3677632a761c6756e95a23aef40ed5389.

**Comment by AlexLaviolette** [comment]
Currently in our office we use slack-gamebot for a [Rocket League](http://www.rocketleaguegame.com/) ladder. 

There are some pretty large skill discrepancies between players which makes for some pretty competitive and balanced 2v1 or 3v2 matches - allowing unbalanced teams lets us increase the stakes and fun for those type of matchups.

**Comment by dblock** [comment]
Thanks @AlexLaviolette. I'll add a `set` command that makes balanced games optional for a team.

Also #126 could help with nomenclature of the bot, lots of people use it for all kinds of non-ping-pong or chess type things.

**Comment by dblock** [comment]
Implemented in https://github.com/dblock/slack-gamebot/commit/bd753538de0c128eb7692518d3ecdd93d5e3a0ea.
