### ISSUE TITLE
gamebot reset is not working

### ISSUE THREAD

**Issue by hubbazoot** [dblock/slack-gamebot#138]
I first type "pb reset " and get the response "No matches have been recorded."

When I then type "pb matches" I see a list of games.

**Comment by dblock** [comment]
Is this on your own instance of the bot or on playplay.io? If this is on playplay, what's your team ID?

**Comment by hubbazoot** [comment]
Team ID on playplay.io: T0DM8UQTX

**Comment by hubbazoot** [comment]
@dblock Is there an update on this?

**Comment by dblock** [comment]
It's a bug. I fixed it in https://github.com/dblock/slack-gamebot/commit/acf1e0cdf54c983d4914715f6c502b383e4012d6 and deployed. Try again @hubbazoot?
