### ISSUE TITLE
Tracking doubles matches

### ISSUE THREAD

**Issue by fsbossev** [dblock/slack-gamebot#141]
Is there a way of tracking score when we play doubles?
If not can we have this as a new feature request?
Thanks.

**Comment by dblock** [comment]
It works the same way, when you lose you say `gamebot lost 15:21 21:17 18:21` and the scores are attached to the doubles match, elos are updated per team, etc. What are you not seeing?

**Comment by fsbossev** [comment]
OK maybe I am missing something.
How can I and Player B challenge Player C and Player D to a doubles match?

**Comment by dblock** [comment]
For example `gamebot challenge @WangHoe @ZhangJike with @DengYaping`. The magic keyword is `with`. Does this not work?

**Comment by fsbossev** [comment]
I did not know about that. I will give it a try. Thank you!

**Comment by dblock** [comment]
The [README](https://github.com/dblock/slack-gamebot/blob/master/README.md) has a lot more details! I'll close this for now, reopen if you can't figure it out.
