### ISSUE TITLE
pongbot posted nsfw gifs

### ISSUE THREAD

**Issue by jethrolarson** [dblock/slack-gamebot#142]
Maybe this needs to go to giphy but still:

http://media2.giphy.com/media/nsgQGSsX8Utd6/giphy.gif (NSFW)

**Comment by dblock** [comment]
Yes you should report this to Giphy. Premium teams can disable GIFs.

**Comment by dblock** [comment]
Closing this as a duplicate of https://github.com/dblock/slack-gamebot/issues/137.
