### ISSUE TITLE
unregister incorrectly requires a premium account for self

### ISSUE THREAD

**Issue by gricey432** [dblock/slack-gamebot#148]
In the help message, it says `unregister` is a command you can use on yourself without premium https://github.com/dblock/slack-gamebot/blob/master/slack-gamebot/commands/help.rb#L13

Further down it says `unregister <player>` is a premium feature https://github.com/dblock/slack-gamebot/blob/master/slack-gamebot/commands/help.rb#L44

However in the command itself, all unregister commands are premium, giving me no way to ever opt out of the bot. https://github.com/dblock/slack-gamebot/blob/master/slack-gamebot/commands/unregister.rb

**Comment by dblock** [comment]
You're right, the doc is incorrect. I would take a pull request that either fixes the doc or changes the behavior in the code though. Then again if you PR that I would give you a free premium subscription, so I think you want to fix the doc ;)

**Comment by dblock** [comment]
This is now moot, the bot is now a 2 week trial and all premium features are enabled by default.
