### ISSUE TITLE
`@pongbot lost` recorded a loss to the wrong user

### ISSUE THREAD

**Issue by rclmenezes** [dblock/slack-gamebot#151]
A user used `@pongbot lost` to record a loss. However, they forgot to specify the winner so the loss was recorded to someone else (who either challenged the user forever ago or maybe it chose the top player because of a bug).

As an aside, it would be nice for captain to alter/fix scores of previous games.

**Comment by dblock** [comment]
It probably recorded the loss against a previous challenge. This is a dup of https://github.com/dblock/slack-gamebot/issues/28, challenges older than, say, 24 hours should just expire. Will close this one.

Opened https://github.com/dblock/slack-gamebot/issues/152 for the alter/fix scores suggestion.

**Comment by rclmenezes** [comment]
Thanks!
