### ISSUE TITLE
Challenge someone (anyone) to a game

### ISSUE THREAD

**Issue by dblock** [dblock/slack-gamebot#166]
Challenge someone, anyone. Any player can accept an open challenge.

Challenging a specific random player is #33.

**Comment by switmer** [comment]
+1 

I think this would drive much more game play. People often don't know who's available - so just signaling that you want to play a game - allows other _free_ people to opt in. Challenging someone who may be busy creates a _somewhat awkward_ experience where there are more declines or open challenges out there while someone is in a meeting and can't respond. To me, this should be the default behavior of the bot.

I'd like to see "@pongbot challenge" accept no player name - and just start an open challenge...
This seems like the simplest implementation. Alternatively: @pongbot challenge anyone.

**Comment by dblock** [comment]
I like this suggestion @switmer. Want to take a stab at it?

**Comment by switmer** [comment]
@dblock Unfortunately - I'm just a UX guy with a github login.

**Comment by dblock** [comment]
@switmer I've implemented this with `challenge @here`. Give it a try?

**Comment by switmer** [comment]
Oh interesting way to solve that. Sweet - I'll give that a go!
