### ISSUE TITLE
Points at stake for a match between two players

### ISSUE THREAD

**Issue by dblock** [dblock/slack-gamebot#168]

**Comment by abarracu** [comment]
Up

**Comment by dcazzaniga** [comment]
Would be a great improvement.

**Comment by dblock** [comment]
I implemented something better I think :) With elo ranking the game is worth different amount of points to different players. I made the equivalent of `challenge` called `challenge?`.

When it's worth the same:

```
pongbot challenge? someone
dblock challenging someone to a match is worth 48 elo.
```

When it's worth different elo.

```
pongbot challenge? someone
dblock challenging someone to a match is worth 53 and 55 elo.
```

Works with groups, unbalanced teams, etc.

Live now.

LMK what you think?
