### ISSUE TITLE
Heroku deploy failing - ruby 2.3.1 not supported on Heroku-18 stack

### ISSUE THREAD

**Issue by andpoi** [dblock/slack-gamebot#171]
When you try to deploy via Heroku, it gives you this error. Is it possible to upgrade ruby versions?

 !
 !     An error occurred while installing ruby-2.3.1
 !     
 !     This version of Ruby is not available on Heroku-18. The minimum supported version
 !     of Ruby on the Heroku-18 stack can found at:
 !     
 !     https://devcenter.heroku.com/articles/ruby-support#supported-runtimes
 !
 !     Push rejected, failed to compile Ruby app.
 !     Push failed

**Comment by dblock** [comment]
Certainly, please PR.

**Comment by dblock** [comment]
2.3.1 is old, closing
