### ISSUE TITLE
Can not add bot again after delete the App

### ISSUE THREAD

**Issue by antfig** [dblock/slack-gamebot#184]
The first time I installed the app everything worked fine, but then after removing the app the next time I added doesn't work anymore. 
I don't know if this is a known issue.

Thanks

**Comment by dblock** [comment]
You'll have to be more specific, please.

If you're doing this on https://www.playplay.io, please email me at dblock at dblock dot org with your team id and I can help you out.

If you're doing this on your own deployment, try restarting the bot and adding after, does this help?

**Comment by dblock** [comment]
Fixed in https://github.com/dblock/slack-gamebot/commit/ff380c0da5ae1b23d0a6bef647e7d7b9b776e53d and https://github.com/slack-ruby/slack-ruby-client/pull/309
