### ISSUE TITLE
Allow player to request win/loss history with another player

### ISSUE THREAD

**Issue by wrgoldstein** [dblock/slack-gamebot#20]
Something like 

`pongbot history dblock`

returning

```
william: 10 wins, dblock: 4 wins
```

**Comment by dblock** [comment]
Slack-gamebot actually provides the complete [match](https://github.com/dblock/slack-gamebot/blob/master/app/models/match.rb) history. So you should be able to expose something a lot more interesting than just totals. Maybe a graph? Trends? :)

**Comment by wrgoldstein** [comment]
:open_mouth: omg graphs

**Comment by dblock** [comment]
I was thinking a bit about what this would look like.

When you specify no users it's about you.

```
pongbot matches

dblock defeated owen 10 times, owen defeated dblock 12 times
dblock defeated will 2 times
```

This should probably support seasons, not sure how that syntax would work. Maybe by default (and to start) we only show current season, which will require more work on the match model.

When you specify multiple users, you basically get matches where both users played (which is a good superset of the above example).

```
pongbot matches dblock owen

dblock defeated owen 10 times, owen defeated dblock 12 times
james and jesse defeated dblock and will 1 time
```
