### ISSUE TITLE
Allow disabling GIFs

### ISSUE THREAD

**Issue by dblock** [dblock/slack-gamebot#40]
Like https://github.com/mziwisky/slack-gamebot/commit/00b1d30b4c628aced9e36c5c179e52aacc2dc4a5 but backwards. We want an "enabled" option which is `true` by default.

**Comment by seonghuhn** [comment]
How exactly do we turn it off? `gamebot images disabled`?

**Comment by dblock** [comment]
@seonghuhn This is a feature request, it's not implemented. Please feel free to help with a PR.

**Comment by seonghuhn** [comment]
@dblock Thanks for replying. I misunderstood, I thought it was done based on the commit referenced. Maybe I could help out. :-)

**Comment by dblock** [comment]
@seonghuhn I found that code in a fork by @mziwisky, and opened a feature request. See my notes above of what I'd like to actually be implemented here. Give it a shot, I'll help out!

**Comment by dblock** [comment]
I've added a `send_gifs` option that can also be set via `ENV['SLACK_RUBY_BOT_SET_GIFS']` in https://github.com/dblock/slack-ruby-bot/commit/0b9bba3aa97115970d34ff98f4ba48f1c946f47c

**Comment by dblock** [comment]
I actually just released slack-ruby-bot 0.5.0 so this is should now "just work".
