### ISSUE TITLE
Resetting teams with a '.' in the name doesn't work

### ISSUE THREAD

**Issue by bruceoite** [dblock/slack-gamebot#67]
Hey there,
  Our team name is something like 'Website.com Delivery'. When I run the command 'reset', it tells me:
Invalid team name, confirm with ​reset Website.com Delivery.

If I run 'reset Website.com Delivery' it tells us the exact same thing.
So my guess is that the issue lies in line 9 of commands/reset.rb:
```
elsif !match.names.include?('expression') || match['expression'] != user.team.name
```
I sadly don't know enough about Ruby to fix this myself. I am really trying to figure out how that line works.

Thanks!

**Comment by dblock** [comment]
Right on. I'll take a look, but feel free to beat me to it, it's always a good idea to start with a spec.

**Comment by dblock** [comment]
This is tricky, Slack replaces something like Pets.com by an URL, so you get `'<http://Pets.com|Pets.com> Delivery'` instead of `Pets.com Delivery`.

**Comment by dblock** [comment]
I've deployed a change that lets you reset both with team name and team ID. Team ID makes as much sense and won't get parsed and replaced by Slack.

**Comment by bruceoite** [comment]
Thanks for the quick fix!
