### ISSUE TITLE
Seeing matches from all teams

### ISSUE THREAD

**Issue by bruceoite** [dblock/slack-gamebot#68]
Are we supposed to see matches from all teams when we run the matches command? I thought it was just an issue with our team, since we also can't reset, but I added the bot to a new slack team and had the same issue. I know that it isn't example data since matches from my original team show up in the new team.

If this is working as intended, can we have a setting to just show our matches?

**Comment by dblock** [comment]
A fix for this has been deployed to playplay.io, thanks for reporting.
