### ISSUE TITLE
Bot responds to anything/anyone if it has the word "sucks" in the sentence.

### ISSUE THREAD

**Issue by andpoi** [dblock/slack-gamebot#76]
Put two bots in the same room and type "you suck". Watch what unfolds.

**Comment by dblock** [comment]
Oh no! Should probably not respond to bot messages for starters, definitely not to `you suck`. @andpoi, do you think it should be restricted further?

**Comment by dblock** [comment]
I simplified this, just responding to `you suck` and `sucks` is enough.
