### ISSUE TITLE
Allow losers to challenge and concede in one command

### ISSUE THREAD

**Issue by wrgoldstein** [dblock/slack-gamebot#78]
We often play games first and then record them.  Currently the loser then challenges the winner, the winner accepts, and the loser concedes.  Three steps, where there should only be one.

Perhaps `pongbot lost to @owen` should have this result if there are no open games for you.

**Comment by dblock** [comment]
This is a great suggestion @wrgoldstein.

**Comment by dblock** [comment]
@wrgoldstein this is live on http://playplay.io now.
