### ISSUE TITLE
Remove players

### ISSUE THREAD

**Issue by eneko** [dblock/slack-gamebot#86]
Ability to remove players that no longer want to play or no longer work at the company.

**Comment by dblock** [comment]
:+1: 

Want to try to implement this @eneko or I can prioritize this if http://playplay.io/#sponsors ;)

**Comment by eneko** [comment]
I could give it a try, but haven't set up a dev environment yet. Will try.

**Comment by dblock** [comment]
I think we want captains to be able to `unregister @name` and players to do `unregister` themselves. That shouldn't delete the user record though, that would break seasons history, existing challenges, etc, but probably mark the user deleted and show `<deleted>` in history or stats.

**Comment by eneko** [comment]
Makes sense. I think the removed users should no longer appear on leaderboards, but it would be good to keep them on the matches history.

**Comment by dblock** [comment]
I've implemented `unregister` in https://github.com/dblock/slack-gamebot/commit/d3379293f0c502fd97598efc680ed68d5ad5639c. It will make its way to playplay.io in the next 24 hours.

**Comment by dblock** [comment]
Deployed.

https://twitter.com/playplayio/status/753954352511844353

<img width="391" alt="screen shot 2016-07-15 at 10 06 23 am" src="https://cloud.githubusercontent.com/assets/542335/16877003/3bd392da-4a74-11e6-9ee8-a90d9f2a91d2.png">
