### ISSUE TITLE
Username obfuscation in 'leaderboard' output

### ISSUE THREAD

**Issue by jbirdkerr** [dblock/slack-gamebot#88]
Give users the ability to obfuscate the output of the 'leaderboard' command to prevent the Slack "highlight & ping" mechanism from alerting users every time someone checks the leaderboard. Obfuscation in this case could be "j<space>birdkerr" instead of "jbirdkerr".

**Comment by dblock** [comment]
Users can now set their own nicknames via `set nickname [name]`, so those annoyed by the notifications can just rename themselves in leaderboards. Supports emoji.

![nickname](https://cloud.githubusercontent.com/assets/542335/17527282/b83c03a2-5e38-11e6-8351-ad079fc0ee3f.gif)
